apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: spark-2:2.4.3
    context: Spark-over-Docker
deploy:
  kubectl:
    manifests:
    - Spark-over-Docker/mysql-pod.yaml
    - Spark-over-Docker/spark-master-pod.yaml
    - Spark-over-Docker/spark-worker-1-pod.yaml
