version: '3'
services:
  spark-master:
    image: spark-2:2.4.4
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
#      SPARK_HISTORY_OPTS: spark.history.fs.logDirectory=file:/tmp/spark-events
    ports:
      - "4040:4040"
      - "6066:6066"
      - "7077:7077"
      - "8080:8080"
#      - "8081:8081"
      - "8888:8888"
      - "18080:18080"
      - "20888:20888"
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/data  
    networks:
      - backend

  spark-worker-1:
    image: spark-2:2.4.4
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./conf/spark-worker-1:/conf
#      - ./data:/data
    networks:
      - backend
volumes:
    conf:
      driver: overlay2
#    data:
#      driver: overlay2

networks:
    backend:
      driver: overlay
