version: "3"
services:
  spark-master:
    image: spark-2:2.4.4
    networks:
      - docknet
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure    
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
    ports:
      - "4040:4040"
      - "6066:6066"
#      - "7077:7077"
      - "8080:8080"
      - "8888:8888"
      - "10000:10000"
      - "10080:10080"
      - "20080:20080"
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/data  

  spark-worker-1:
    image: spark-2:2.4.4
    networks:
      - docknet
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure    
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 127.0.0.1
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/data

networks:
  docknet:
    driver: overlay

volumes:
  conf:
  data:
