FROM nvidia/cuda

RUN apt -y update
RUN apt-get -y install apt-utils curl

# PIP and python packages
RUN apt-get -y install python3-pip
RUN pip3 install jupyter matplotlib seaborn xgboost scikit-learn

# TensorFlow-GPU 2.x
RUN pip3 install --pre -U tensorflow-gpu
