apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: spark
spec:
  containers:
  - args:
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: xxxxxxxxx
    ports:
    - containerPort: 3306
    image: mysql:latest
    name: mysql
    resources: {}
  restartPolicy: OnFailure
  tolerations:
    - effect: NoExecute
      key: "node.kubernetes.io"
      operator: Equal
      value: "not-ready"
    - effect: NoSchedule
      key: "node-role.kubernetes.io"
      operator: Equal
      value: "master"
status: {}
