kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pyspark-clusterrolebinding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: pyspark-clusterrole
subjects:
  - kind: ServiceAccount
    name: system
    namespace: spark
