kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pyspark--clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
