apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: spark
  name: spark-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spark
    spec:
      containers:
      - args:
        - bin/pyspark
        - --master
        - spark://spark-master:7077
        env:
        - name: MASTER
          value: spark://spark-master:7077
        - name: SPARK_CONF_DIR
          value: /conf
        - name: SPARK_PUBLIC_DNS
          value: 127.0.0.1
        image: spark-2:2.4.4
        name: spark-jupyter
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /conf
          name: spark-master-claim0
        - mountPath: data
          name: spark-master-claim1
      hostname: spark-jupyter
      restartPolicy: Always
      volumes:
      - name: spark-master-claim0
        persistentVolumeClaim:
          claimName: spark-master-claim0
      - name: spark-master-claim1
        persistentVolumeClaim:
          claimName: spark-master-claim1
      tolerations:
      - effect: NoExecute
        key: "node.kubernetes.io"
        operator: Equal
        value: "not-ready"
      - effect: NoSchedule
        key: "node-role.kubernetes.io"
        operator: Equal
        value: "master"
status: {}
