apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master-claim0
  name: spark-master-claim0
spec:
  storageClassName: spark-master-conf-pv-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
status: {}
