apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: spark-worker-1
  name: spark-worker-1
spec:
  selector:
    matchLabels:
      app: spark-worker-1
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spark-worker-1
    spec:
      containers:
      - args:
        - bin/spark-class
        - org.apache.spark.deploy.worker.Worker
        - spark://spark-master:7077
        env:
        - name: SPARK_CONF_DIR
          value: /conf
        - name: SPARK_PUBLIC_DNS
          value: 127.0.0.1
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: 2g
        - name: SPARK_WORKER_PORT
          value: "8881"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        image: spark-3:3.0.1
        name: spark-worker-1
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /conf
          name: spark-worker-1-claim0
        - mountPath: /data
          name: spark-worker-1-claim1
      hostname: spark-worker-1
      restartPolicy: Always
      volumes:
      - name: spark-worker-1-claim0
        persistentVolumeClaim:
          claimName: spark-worker-1-claim0
      - name: spark-worker-1-claim1
        persistentVolumeClaim:
          claimName: spark-worker-1-claim1
      tolerations:
      - effect: NoExecute
        key: "node.kubernetes.io"
        operator: Equal
        value: "not-ready"
      - effect: NoSchedule
        key: "node-role.kubernetes.io"
        operator: Equal
        value: "master"
status: {}
