apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1
  name: spark-worker-1
  namespace: spark
spec:
  containers:
  - args:
    - bin/spark-class
    - org.apache.spark.deploy.worker.Worker
    - spark://spark-master:7077
    env:
    - name: SPARK_CONF_DIR
      value: /conf
    - name: SPARK_WORKER_CORES
      value: "2"
    - name: SPARK_WORKER_MEMORY
      value: 2g
    - name: SPARK_WORKER_PORT
      value: "8881"
    - name: SPARK_WORKER_WEBUI_PORT
      value: "8081"
    - name: SPARK_PUBLIC_DNS
      value: "spark.svc.cluster.local"
    image: spark-2:2.4.3
    name: spark-worker-1
    resources: {}
  restartPolicy: OnFailure
status: {}
