apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: spark
  name: spark-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spark
    spec:
      containers:
      - args:
        - bin/spark-submit 
        - --class
        - org.apache.spark.examples.SparkPi
        - --master
        - k8s://10.96.0.1:443
        - --conf
        - spark.kubernetes.namespace=spark
        - --conf
        - spark.kubernetes.authenticate.driver.serviceAccountName=spark
        - --conf
        - spark.local.dir=/tmp/spark-local
        - --conf
        - spark.app.name=spark-pi
        - --conf
        - spark.kubernetes.container.image=spark-2:2.4.4
        - --conf
        - spark.executor.instances=1
        - local:///usr/local/spark-2.4.4-bin-hadoop2.7/examples/jars/spark-examples_2.11-2.4.4.jar
        env:
        - name: SPARK_PUBLIC_DNS
          value: 127.0.0.1
        image: spark-2:2.4.4
        name: spark-submit
        ports:
        - containerPort: 8888
        resources: {}
      hostname: spark-submit
      restartPolicy: Always
      tolerations:
      - effect: NoExecute
        key: "node.kubernetes.io"
        operator: Equal
        value: "not-ready"
      - effect: NoSchedule
        key: "node-role.kubernetes.io"
        operator: Equal
        value: "master"
status: {}
