apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: spark
  name: spark-jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spark
    spec:
      containers:
      - args:
        - bin/pyspark
        - --master
        - k8s://10.96.0.1:443
        - --conf
        - spark.kubernetes.authenticate.driver.serviceAccountName=spark
        - --conf
        - spark.kubernetes.container.image=spark-2:2.4.4
        - --conf
        - spark.executor.instances=1 
        - --conf
        - spark.kubernetes.submission.waitAppCompletion=true
        - --conf
        - spark.kubernetes.namespace=spark
        - --conf
        - spark.dynamicAllocation.enabled=true
        env:
        - name: SPARK_PUBLIC_DNS
          value: 127.0.0.1
        image: spark-2:2.4.4
        name: spark-jupyter
        ports:
        - containerPort: 8888
        resources: {}
      hostname: spark-jupyter
      restartPolicy: Always
      tolerations:
      - effect: NoExecute
        key: "node.kubernetes.io"
        operator: Equal
        value: "not-ready"
      - effect: NoSchedule
        key: "node-role.kubernetes.io"
        operator: Equal
        value: "master"
status: {}
