apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: spark-master-data-pv-class
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
