kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv-volume
  labels:
    type: local
spec:
  storageClassName: data-pv-volume
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./data"
