apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker-1-claim1
  name: spark-worker-1-claim1
spec:
  storageClassName: spark-worker-1-data-pv-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
status: {}
