apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
  namespace: spark
spec:
  containers:
  - args:
    - bin/spark-class
    - org.apache.spark.deploy.master.Master
    - -h
    - spark-master
    env:
    - name: MASTER
      value: spark://spark-master:7077
    - name: SPARK_CONF_DIR
      value: /conf
    - name: SPARK_PUBLIC_DNS
      value: "spark.svc.cluster.local"
    image: spark-2:2.2.1
    name: spark-master
    ports:
    - containerPort: 4040
    - containerPort: 6066
    - containerPort: 7077
    - containerPort: 8080
    - containerPort: 10000
    volumeMounts:
    - name: conf
      mountPath: /conf
    - name: data
      mountPath: /data
    resources: {}
  restartPolicy: OnFailure
  volumes:
  - name: conf
    hostPath:
      path: /root/conf/spark-master
      type: Directory
  - name: data
    hostPath:
      path: /root/data
      type: Directory
status: {}
