apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-worker-1-conf-pv-volume
  labels:
    type: local
spec:
  storageClassName: spark-worker-1-conf-pv-class
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/conf/spark-worker-1"
